name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ['1.19', '1.20', '1.21']

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        cache-dependency-path: go.sum
        go-version: ${{ matrix.go_version }}

    - name: Test
      run:
        go test -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-cache: true
        version: v1.55
      if: always()
